version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  yig_api:
    container_name: yig_api
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - yig_postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    stdin_open: true
    tty: true

  yig_postgres:
    container_name: yig_postgres
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    container_name: yig_postgres
    hostname: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  yig_frontend:
    container_name: yig_frontend
    restart: always
    build:  
      context: ./frontend
      dockerfile: Dockerfile
    container_name: yig_frontend
    image: yig_frontend_image
    depends_on:
      - yig_api
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d
    ports:
      - 81:80
