# Generated by Django 4.0.1 on 2022-01-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_create_generator_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generator',
            old_name='video',
            new_name='title',
        ),
        migrations.AddField(
            model_name='generator',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
    ]
