# Generated by Django 4.0.1 on 2022-01-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_created_some_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_video_id',
            field=models.CharField(default='dsffgvidjg', max_length=256),
            preserve_default=False,
        ),
    ]
