# Generated by Django 4.0.1 on 2022-01-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_extended_channel_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_subscribers',
            field=models.IntegerField(null=True),
        ),
    ]
