# Generated by Django 4.0.1 on 2022-01-31 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_extended_channel_model_to_store_subscriber_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
