# Generated by Django 3.2 on 2022-03-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_extendedusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='extended_user',
            field=models.ManyToManyField(blank=True, null=True, to='api.ExtendedUserModel'),
        ),
    ]
